-- Step 3: Seed workflow steps and permission settings

-- Seed default workflow steps for orders
INSERT INTO public.workflow_steps (entity_type, step_order, step_key, step_name, step_name_cn, responsible_roles, blocked_by_steps, auto_complete) VALUES
('order', 1, 'campaign_created', 'Campaign Created', '营销活动创建', ARRAY['marketing'], '{}', false),
('order', 2, 'lead_created', 'Lead Created', '线索创建', ARRAY['marketing'], '{}', false),
('order', 3, 'order_created', 'Order Created', '订单创建', ARRAY['sales'], '{}', true),
('order', 4, 'sourcing_started', 'Sourcing Started', '开始采购', ARRAY['sourcing', 'marketing', 'sales'], ARRAY['order_created'], false),
('order', 5, 'quotation_sent', 'Quotation Sent', '报价已发送', ARRAY['sales'], ARRAY['sourcing_started'], false),
('order', 6, 'factory_qc_check', 'Factory QC Check', '工厂质检', ARRAY['qc'], ARRAY['sourcing_started'], false),
('order', 7, 'order_confirmed', 'Order Confirmed', '订单确认', ARRAY['sales'], ARRAY['quotation_sent'], false),
('order', 8, 'po_created', 'PO Created', '采购单创建', ARRAY['merchandising'], ARRAY['order_confirmed'], false),
('order', 9, 'customer_deposit_collected', 'Customer Deposit Collected', '客户定金收取', ARRAY['sales', 'finance'], ARRAY['po_created'], false),
('order', 10, 'factory_deposit_paid', 'Factory Deposit Paid', '工厂定金支付', ARRAY['finance'], ARRAY['customer_deposit_collected'], false),
('order', 11, 'production_started', 'Production Started', '生产开始', ARRAY['production'], ARRAY['factory_deposit_paid'], false),
('order', 12, 'qc_scheduled', 'QC Scheduled', '质检安排', ARRAY['qc'], ARRAY['production_started'], false),
('order', 13, 'qc_completed', 'QC Completed', '质检完成', ARRAY['qc'], ARRAY['qc_scheduled'], false),
('order', 14, 'customer_balance_collected', 'Customer Balance Collected', '客户尾款收取', ARRAY['sales', 'finance'], ARRAY['qc_completed'], false),
('order', 15, 'factory_balance_paid', 'Factory Balance Paid', '工厂尾款支付', ARRAY['finance'], ARRAY['customer_balance_collected'], false),
('order', 16, 'shipment_created', 'Shipment Created', '发货安排', ARRAY['logistics'], ARRAY['qc_completed'], false),
('order', 17, 'delivery_tracking', 'Delivery Tracking', '物流跟踪', ARRAY['logistics'], ARRAY['shipment_created'], false),
('order', 18, 'delivered', 'Delivered', '已交付', ARRAY['logistics'], ARRAY['delivery_tracking'], false),
('order', 19, 'cash_flow_updated', 'Cash Flow Updated', '现金流更新', ARRAY['finance'], ARRAY['delivered'], false),
('order', 20, 'ledger_updated', 'Customer Ledger Updated', '客户账本更新', ARRAY['finance'], ARRAY['delivered'], false),
('order', 21, 'success_story', 'Success Story', '成功案例', ARRAY['marketing'], ARRAY['delivered'], false),
('order', 22, 'project_analysis', 'Project Analysis', '项目分析', ARRAY['manager', 'hr'], ARRAY['delivered'], false),
('order', 23, 'next_campaign', 'Next Campaign', '下一轮营销', ARRAY['marketing'], ARRAY['success_story'], false);

-- Seed default permission settings
INSERT INTO public.permission_settings (role, module, can_view, can_create, can_edit, can_delete, can_assign) VALUES
-- Manager
('manager', 'leads', true, true, true, true, true),
('manager', 'customers', true, true, true, true, true),
('manager', 'sourcing', true, true, true, true, true),
('manager', 'quotations', true, true, true, true, true),
('manager', 'orders', true, true, true, true, true),
('manager', 'suppliers', true, true, true, true, true),
('manager', 'purchase_orders', true, true, true, true, true),
('manager', 'qc', true, true, true, true, true),
('manager', 'shipments', true, true, true, true, true),
('manager', 'finance', true, true, true, true, true),
('manager', 'users', true, true, true, true, true),
-- Sales
('sales', 'leads', true, true, true, false, false),
('sales', 'customers', true, true, true, false, false),
('sales', 'sourcing', true, false, false, false, false),
('sales', 'quotations', true, true, true, false, false),
('sales', 'orders', true, true, true, false, true),
('sales', 'suppliers', true, false, false, false, false),
('sales', 'purchase_orders', true, false, false, false, false),
('sales', 'qc', true, false, false, false, false),
('sales', 'shipments', true, false, false, false, false),
('sales', 'finance', false, false, false, false, false),
-- Sourcing
('sourcing', 'leads', true, false, false, false, false),
('sourcing', 'customers', true, false, false, false, false),
('sourcing', 'sourcing', true, true, true, true, true),
('sourcing', 'quotations', true, true, true, true, false),
('sourcing', 'orders', true, false, true, false, false),
('sourcing', 'suppliers', true, true, true, true, true),
('sourcing', 'purchase_orders', true, true, true, false, false),
('sourcing', 'qc', true, false, false, false, false),
('sourcing', 'shipments', true, false, false, false, false),
('sourcing', 'finance', false, false, false, false, false),
-- Merchandising
('merchandising', 'leads', false, false, false, false, false),
('merchandising', 'customers', true, false, false, false, false),
('merchandising', 'sourcing', true, false, true, false, false),
('merchandising', 'quotations', true, false, true, false, false),
('merchandising', 'orders', true, false, true, false, false),
('merchandising', 'suppliers', true, false, true, false, false),
('merchandising', 'purchase_orders', true, true, true, true, true),
('merchandising', 'qc', true, false, false, false, false),
('merchandising', 'shipments', true, false, false, false, false),
('merchandising', 'finance', false, false, false, false, false),
-- QC
('qc', 'orders', true, false, false, false, false),
('qc', 'suppliers', true, false, true, false, false),
('qc', 'purchase_orders', true, false, true, false, false),
('qc', 'qc', true, true, true, true, true),
('qc', 'shipments', true, false, false, false, false),
-- Logistics
('logistics', 'orders', true, false, true, false, false),
('logistics', 'purchase_orders', true, false, true, false, false),
('logistics', 'qc', true, false, false, false, false),
('logistics', 'shipments', true, true, true, true, true),
('logistics', 'finance', true, false, false, false, false),
-- Finance
('finance', 'customers', true, false, false, false, false),
('finance', 'orders', true, false, true, false, false),
('finance', 'purchase_orders', true, false, true, false, false),
('finance', 'shipments', true, false, true, false, false),
('finance', 'finance', true, true, true, true, true),
-- Production
('production', 'orders', true, false, true, false, false),
('production', 'purchase_orders', true, false, true, false, false),
('production', 'qc', true, false, true, false, false),
-- Marketing
('marketing', 'leads', true, true, true, true, true),
('marketing', 'customers', true, false, true, false, false),
('marketing', 'sourcing', true, false, true, false, false),
('marketing', 'quotations', true, false, true, false, false),
('marketing', 'orders', true, false, true, false, false),
-- HR
('hr', 'users', true, true, true, true, true);